services:
  wallet-app:
    build: .
    container_name: wallet-service
    environment:
      SPRING_DATASOURCE_URL: ********
      SPRING_DATASOURCE_USERNAME: ********
      SPRING_DATASOURCE_PASSWORD: ********
    ports:
      - "8080:8080"
